### ISSUE TITLE
Announce closing party on website

### ISSUE THREAD

**Issue by marcoow** [emberfest/emberfest.github.io#195]
We should announce the closing party on Friday night on the website. We should have another entry at the end of the schedule table, saying _"18:30–22:00 Closing Diner at Vestauranten"_ and then below the content box with the venue data another content box like this:

<img width="623" alt="Bildschirmfoto 2019-09-25 um 13 52 42" src="https://user-images.githubusercontent.com/1510/65598513-e7990180-df9b-11e9-9980-96db71ae86a9.png">

venue photo: 
![153787_3-dgibyen-vestauranten](https://user-images.githubusercontent.com/1510/65598520-ecf64c00-df9b-11e9-8afa-c757b452dedf.jpg)

**Comment by jkintscher** [comment]
I’d definitely add it to the schedule, but should we announce the venue details along with that?
In the previous years we shared the pictures and details about the place in our opening remarks on the first day, instead of the newsletter or website.

But if you guys decided that the reveal should be made on the website, I’m good with that, of couse.

**Comment by marcoow** [comment]
I think it's a nice extra to have on the website that could help sell tickets. Also, if it's in the schedule only, people will likely miss it and in the worst case book their returns flights for Friday night already.
