### ISSUE TITLE
Add About Us section

### ISSUE THREAD

**Issue by balinterdi** [emberfest/emberfest.github.io#30]
This should probably still go to the landing page itself, well below the fold. It could have our pictures and maybe a few sentences about each of us (or just the name and "role" or company).

**Comment by balinterdi** [comment]
@alexspeller @jkintscher @marcoow @joachimhs Could you provide a link to a mugshot of yours and a 1-2 line bio? Thank you.

**Comment by marcoow** [comment]
https://avatars1.githubusercontent.com/u/1510?v=4&s=460

**Comment by marcoow** [comment]
Marco is the founder of simplabs, a consultancy based in Munich, Germany specializing in Ember.js and Elixir/Phoenix. He has been working in Web Engineering since the late 90s and used many different languages and frameworks in project of all scale for enterprise clients and startups. Marco is passionate about conventions-based tools that liberate through imposing constraints.
